/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.Configuracion;

import Logica.Conexion;
import Objetos.Carrera;
import Objetos.Profesor;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Objects;

/**
 *
 * @author dario
 */
public class FormularioProfesor extends javax.swing.JFrame {
    Profesor profesor;

    ArrayList<Carrera> carreras;
    /**
     * Creates new form ModificarProfesor
     */
    public FormularioProfesor(Profesor profesor) {
        this.profesor = profesor;
        this.carreras = Carrera.getCarreras();
        initComponents();
        dniProfesor.setText(profesor.getDni().toString());
        nombreProfesor.setText(profesor.getNombre());
        apellidoProfesor.setText(profesor.getApellido());
        comboboxCarreras.setSelectedItem(profesor.getCarrera());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    public FormularioProfesor(){
        this.carreras = Carrera.getCarreras();
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dniProfesor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoProfesor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboboxCarreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Profesor");

        jLabel1.setText("DNI:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Carrera:");

        comboboxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(carreras.toArray(new Carrera[0])));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreProfesor)
                            .addComponent(dniProfesor)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxCarreras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //su el profesor es diferente de null, es decir que estou modificando un profesor existente ejecuta el codigo para modificarlo
        if(profesor!=null) {
            profesor.setDni(Integer.parseInt(dniProfesor.getText()));
            profesor.setNombre(nombreProfesor.getText());
            profesor.setApellido(apellidoProfesor.getText());
            profesor.setCarrera((Carrera) Objects.requireNonNull(comboboxCarreras.getSelectedItem()));
            System.out.println("Cargo todo");
        }else{
            //caso contrario estoy agregando un profesor, por lo tanto creo uno nuevo y lo subo a la base de datos
            profesor = new Profesor(Integer.parseInt(dniProfesor.getText()),nombreProfesor.getText(),apellidoProfesor.getText(),(Carrera) Objects.requireNonNull(comboboxCarreras.getSelectedItem()));
            profesor.cargarDatosProfesor();
        }
        //cierra la ventana sin cerrar el programa entero
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public Profesor getProfesor(){return profesor;}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoProfesor;
    private javax.swing.JComboBox<Carrera> comboboxCarreras;
    private javax.swing.JTextField dniProfesor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreProfesor;
    // End of variables declaration//GEN-END:variables
}
