/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.Configuracion;

import Logica.Conexion;
import Logica.parametrosDeConfiguracion;
import Objetos.Carrera;
import Objetos.Profesor;
import Objetos.Salon;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.io.File;
import java.util.ArrayList;
import java.util.regex.Pattern;

/**
 *
 * @author dario
 */
public class pantallaConfig2 extends javax.swing.JPanel {
    private ArrayList<Profesor> profesores;
    private ArrayList<Salon> salones;
    private ArrayList<Carrera> carreras;

    /**
     * Creates new form pantallaConfig2
     */
    public pantallaConfig2(JRootPane pantalla) {
        //relaciona el array interno de la clase con los array de la pantalla configuracion (estan sincronizados, cualquier cambien en unoo afecta el otro)
        profesores = Profesor.getProfesores();
        carreras = Carrera.getCarreras();
        salones = Salon.getSalones();
        //carga de componentes
        initComponents();

        if(parametrosDeConfiguracion.getTema().equals("Oscuro")){
            ponerTemaOscuro();
            botonTema.setText("Tema Claro");
        } else if (parametrosDeConfiguracion.getTema().equals("Claro")) {
            ponerTemaClaro();
            botonTema.setText("Tema Oscuro");
        }
        pantalla.revalidate();
        pantalla.repaint();
        cambiarVisibilidad(false);
        comboboxTamanoModificar.setSelectedItem(null);
        comboboxProfesores.setSelectedItem(null);
        comboboxSalones.setSelectedItem(null);
        comboboxCarrerasModificarProfesor.setSelectedItem(null);
        comboboxTamanoAgregar.setSelectedItem(null);
        comboboxCarreras.setSelectedItem(null);
        comboboxCarrerasAgregar.setSelectedItem(null);

    }
    private void ponerTemaOscuro(){
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void ponerTemaClaro(){
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void cambiarVisibilidad(boolean bool){
        jLabel6.setVisible(bool);
        jLabel4.setVisible(bool);
        nombreModificar.setVisible(bool);
        comboboxTamanoModificar.setVisible(bool);
        proyectorModificar.setVisible(bool);
        TVModificar.setVisible(bool);
        VGAModificar.setVisible(bool);
        HDMIModificar.setVisible(bool);
        audioModificar.setVisible(bool);
        interlockModificar.setVisible(bool);
        conversorModificar.setVisible(bool);
        salonModificar.setVisible(bool);
        jLabel12.setVisible(bool);
        jLabel13.setVisible(bool);
        jLabel14.setVisible(bool);
        jLabel15.setVisible(bool);
        dniProfesorModificar.setVisible(bool);
        nombreProfesorModificar.setVisible(bool);
        apellidoProfesorModificar.setVisible(bool);
        comboboxCarrerasModificarProfesor.setVisible(bool);
        modificarProfesor.setVisible(bool);
        jLabel22.setVisible(bool);
        nombreCarreraModificar.setVisible(bool);
        carreraModificar.setVisible(bool);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        Salones = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        comboboxTamanoAgregar = new javax.swing.JComboBox<>();
        TVAgregar = new javax.swing.JCheckBox();
        VGAAgregar = new javax.swing.JCheckBox();
        HDMIAgregar = new javax.swing.JCheckBox();
        interlockAgregar = new javax.swing.JCheckBox();
        audioAgregar = new javax.swing.JCheckBox();
        conversorAgregar = new javax.swing.JCheckBox();
        proyectorAgregar = new javax.swing.JCheckBox();
        salonGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboboxTamanoModificar = new javax.swing.JComboBox<>();
        proyectorModificar = new javax.swing.JCheckBox();
        TVModificar = new javax.swing.JCheckBox();
        VGAModificar = new javax.swing.JCheckBox();
        HDMIModificar = new javax.swing.JCheckBox();
        interlockModificar = new javax.swing.JCheckBox();
        audioModificar = new javax.swing.JCheckBox();
        conversorModificar = new javax.swing.JCheckBox();
        salonModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nombreAgregarSalon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreModificar = new javax.swing.JTextField();
        comboboxSalones = new javax.swing.JComboBox<Salon>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dniProfesorAgregar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombreProfesorAgregar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        apellidoProfesorAgregar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboboxCarrerasAgregar = new javax.swing.JComboBox<>();
        guardarProfesor = new javax.swing.JButton();
        dniProfesorModificar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nombreProfesorModificar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        apellidoProfesorModificar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboboxCarrerasModificarProfesor = new javax.swing.JComboBox<Carrera>(
        );
        modificarProfesor = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboboxProfesores = new javax.swing.JComboBox<>();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        nombreCarreraAgregar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboboxCarreras = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        nombreCarreraModificar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        carreraModificar = new javax.swing.JButton();
        carreraGuardar = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        tabConfiguracion = new javax.swing.JLayeredPane();
        botonTema = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        bdURL = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        bdUser = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        bdPass = new javax.swing.JPasswordField();
        guardarBD = new javax.swing.JButton();
        hacerBackup = new javax.swing.JButton();
        restaurarDesdeBackup = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        botonInterfaz = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Agregar");

        comboboxTamanoAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));

        TVAgregar.setText("Televisor");

        VGAAgregar.setText("Cable VGA");

        HDMIAgregar.setText("Cable HDMI");

        interlockAgregar.setText("Cable interlock 220v");

        audioAgregar.setText("Cable de audio");

        conversorAgregar.setText("Conversor de señal");

        proyectorAgregar.setText("Proyector");

        salonGuardar.setText("Guardar");
        salonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño");

        jLabel2.setText("Modificar");

        jLabel4.setText("Tamaño");

        comboboxTamanoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Pequeño", "Mediano", "Grande" }));

        proyectorModificar.setText("Proyector");

        TVModificar.setText("Televisor");

        VGAModificar.setText("Cable VGA");

        HDMIModificar.setText("Cable HDMI");

        interlockModificar.setText("Cable interlock 220v");

        audioModificar.setText("Cable de audio");

        conversorModificar.setText("Conversor de señal");

        salonModificar.setText("Modificar");
        salonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonModificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Nombre");

        comboboxSalones.setModel(new javax.swing.DefaultComboBoxModel<>(salones.toArray(new Salon[0])));
        comboboxSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxSalonesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboboxTamanoAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TVAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(VGAAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(HDMIAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(interlockAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(audioAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(conversorAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(proyectorAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(salonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboboxTamanoModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(proyectorModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TVModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(VGAModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(HDMIModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(interlockModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(audioModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(conversorModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(salonModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nombreAgregarSalon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nombreModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboboxSalones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboboxTamanoAgregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proyectorAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TVAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VGAAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HDMIAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(interlockAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(audioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conversorAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(salonGuardar))
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreAgregarSalon, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxTamanoModificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proyectorModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TVModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VGAModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HDMIModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interlockModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(audioModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conversorModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(salonModificar))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(comboboxSalones, javax.swing.GroupLayout.Alignment.TRAILING, 0, 260, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboboxSalones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(nombreAgregarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxTamanoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proyectorAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TVAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VGAAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HDMIAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interlockAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conversorAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(salonGuardar))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxTamanoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(proyectorModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TVModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VGAModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HDMIModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interlockModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conversorModificar)
                        .addGap(18, 18, 18)
                        .addComponent(salonModificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Salones.addTab("Salones", jLayeredPane1);

        jLabel7.setText("Agregar");

        jLabel8.setText("Documento");

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Carrera");

        comboboxCarrerasAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(carreras.toArray(new Carrera[0])));

        guardarProfesor.setText("Guardar");
        guardarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProfesorActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        jLabel13.setText("Documento");

        jLabel14.setText("Apellido");

        jLabel15.setText("Carrera");

        comboboxCarrerasModificarProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(carreras.toArray(new Carrera[0])));

        modificarProfesor.setText("Modificar");
        modificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProfesorActionPerformed(evt);
            }
        });

        jLabel16.setText("Modificar");

        jLabel17.setText("Profesor");

        comboboxProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(profesores.toArray(new Profesor[0])));
        comboboxProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxProfesoresActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(dniProfesorAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nombreProfesorAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(apellidoProfesorAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(comboboxCarrerasAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(guardarProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(dniProfesorModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nombreProfesorModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(apellidoProfesorModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(comboboxCarrerasModificarProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(modificarProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(comboboxProfesores, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dniProfesorAgregar)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreProfesorAgregar)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoProfesorAgregar)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxCarrerasAgregar, 0, 260, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(guardarProfesor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dniProfesorModificar)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreProfesorModificar)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoProfesorModificar)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxCarrerasModificarProfesor, 0, 260, Short.MAX_VALUE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(modificarProfesor))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxProfesores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniProfesorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProfesorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoProfesorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxCarrerasAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardarProfesor))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dniProfesorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProfesorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoProfesorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxCarrerasModificarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificarProfesor)))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        Salones.addTab("Profesores", jLayeredPane2);

        jLabel18.setText("Agregar");

        jLabel19.setText("Modificar");

        jLabel20.setText("Nombre de la carrera:");

        comboboxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(carreras.toArray(new Carrera[0])));
        comboboxCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxCarrerasActionPerformed(evt);
            }
        });

        jLabel21.setText("Carrera");

        jLabel22.setText("Nombre");

        carreraModificar.setText("Modificar");
        carreraModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraModificarActionPerformed(evt);
            }
        });

        carreraGuardar.setText("Guardar");
        carreraGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraGuardarActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nombreCarreraAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(comboboxCarreras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nombreCarreraModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(carreraModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(carreraGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCarreraAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(carreraGuardar)))
                        .addGap(70, 70, 70)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nombreCarreraModificar)
                            .addComponent(comboboxCarreras, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carreraModificar)
                .addGap(97, 97, 97))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCarreraAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(carreraGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCarreraModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(carreraModificar)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        Salones.addTab("Carreras", jLayeredPane3);

        botonTema.setText("Tema  Oscuro");
        botonTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTemaActionPerformed(evt);
            }
        });

        jLabel23.setText("Opciones Graficas:");

        jLabel24.setText("Base de datos:");

        jLabel25.setText("URL");

        jLabel26.setText("Usuario");

        jLabel27.setText("Contraseña");

        guardarBD.setText("Guardar");
        guardarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBDActionPerformed(evt);
            }
        });

        hacerBackup.setText("Respaldar base de datos");
        hacerBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerBackupActionPerformed(evt);
            }
        });

        restaurarDesdeBackup.setText("Restaurar desde respaldo");
        restaurarDesdeBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarDesdeBackupActionPerformed(evt);
            }
        });

        jLabel28.setText("Datos de conexión:");

        jLabel29.setText("Copia de respaldo");

        botonInterfaz.setText("Cambiar interfaz");
        botonInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInterfazActionPerformed(evt);
            }
        });

        tabConfiguracion.setLayer(botonTema, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(bdURL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(bdUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(bdPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(guardarBD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(hacerBackup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(restaurarDesdeBackup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabConfiguracion.setLayer(botonInterfaz, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabConfiguracionLayout = new javax.swing.GroupLayout(tabConfiguracion);
        tabConfiguracion.setLayout(tabConfiguracionLayout);
        tabConfiguracionLayout.setHorizontalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(bdURL)
                                .addComponent(bdUser)
                                .addComponent(bdPass, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonInterfaz)))
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(guardarBD))
                    .addComponent(restaurarDesdeBackup)
                    .addComponent(jLabel29)
                    .addComponent(hacerBackup))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        tabConfiguracionLayout.setVerticalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonTema)
                    .addComponent(jLabel28))
                .addGap(4, 4, 4)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonInterfaz))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(bdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bdPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarBD)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(hacerBackup)
                .addGap(18, 18, 18)
                .addComponent(restaurarDesdeBackup)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLayeredPane4.setLayer(tabConfiguracion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Salones.addTab("Configuracion", jLayeredPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salones, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salones, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonGuardarActionPerformed
        new Salon(-1,nombreAgregarSalon.getText(),
                comboboxTamanoAgregar.getSelectedItem().toString(),
                "",
                interlockAgregar.isSelected(),
                VGAAgregar.isSelected(),
                HDMIAgregar.isSelected(),
                audioAgregar.isSelected(),
                conversorAgregar.isSelected(),
                TVAgregar.isSelected(),
                proyectorAgregar.isSelected());

        comboboxSalones.setModel(new DefaultComboBoxModel<>(salones.toArray(new Salon[0])));
        comboboxSalones.setSelectedItem(null);
    }//GEN-LAST:event_salonGuardarActionPerformed


    private void salonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonModificarActionPerformed

        if(comboboxSalones.getSelectedItem() != null){

            Salon salon = (Salon) comboboxSalones.getSelectedItem();

            salon.setTamano(comboboxTamanoModificar.getSelectedItem().toString());
            salon.setProyector(proyectorModificar.isSelected());
            salon.setTV(TVModificar.isSelected());
            salon.setCableHDMI(HDMIModificar.isSelected());
            salon.setCableVGA(VGAModificar.isSelected());
            salon.setInterlock220V(interlockModificar.isSelected());
            salon.setCableAudio(audioModificar.isSelected());
            salon.setConversor(conversorModificar.isSelected());
            salon.setObservaciones("");
            salon.setNombre(nombreModificar.getText());

            cambiarVisibilidad(false);
            comboboxSalones.setSelectedItem(null);
        }

    }//GEN-LAST:event_salonModificarActionPerformed


    private void botonTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTemaActionPerformed
        if(botonTema.getText().equals("Tema Oscuro")){
            ponerTemaOscuro();
            parametrosDeConfiguracion.setTema("Oscuro");
            botonTema.setText("Tema Claro");
        }else {
            ponerTemaClaro();
            parametrosDeConfiguracion.setTema("Claro");
            botonTema.setText("Tema Oscuro");
        }
    }//GEN-LAST:event_botonTemaActionPerformed

    private void guardarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBDActionPerformed
        if(!(bdURL.getText().equals("")||bdUser.getText().equals(""))){
            parametrosDeConfiguracion.setURL(bdURL.getText());
            parametrosDeConfiguracion.setUsuarioSQL(bdUser.getText());
            parametrosDeConfiguracion.setPassSQL(new String(bdPass.getPassword()));
        }else{
            JOptionPane.showMessageDialog(this,"Por favor rellene todos los campos para actualizar la base de datos","error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarBDActionPerformed

    private void hacerBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerBackupActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = chooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File carpetaSeleccionada = chooser.getSelectedFile();
            Conexion.hacerBackup(carpetaSeleccionada.getAbsolutePath());
        }
    }//GEN-LAST:event_hacerBackupActionPerformed

    private void restaurarDesdeBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarDesdeBackupActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.addChoosableFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                Pattern patron = Pattern.compile("\\w+\\.sql$");
                return patron.matcher(file.getName()).find();
            }

            @Override
            public String getDescription() {
                return "Archivos SQL (*.sql)";
            }
        });

        int seleccion = chooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File carpetaSeleccionada = chooser.getSelectedFile();
            System.out.println(carpetaSeleccionada.getAbsolutePath());
            Conexion.restaurarDesdeBackup(carpetaSeleccionada.getAbsolutePath());
        }

    }//GEN-LAST:event_restaurarDesdeBackupActionPerformed

    private void botonInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInterfazActionPerformed

        this.getRootPane().setContentPane(new pantallaConfig1(this.getRootPane()));

        parametrosDeConfiguracion.setInterfazConfiguracion("config1");

    }//GEN-LAST:event_botonInterfazActionPerformed

    private void comboboxSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxSalonesActionPerformed

        if(comboboxSalones.getSelectedItem() != null){

            cambiarVisibilidad(true);

            Salon salon =(Salon)comboboxSalones.getSelectedItem();

            HDMIModificar.setSelected(salon.isCableHDMI());
            VGAModificar.setSelected(salon.isCableVGA());
            TVModificar.setSelected(salon.isTV());
            proyectorModificar.setSelected(salon.isProyector());
            conversorModificar.setSelected(salon.isConversor());
            audioModificar.setSelected(salon.isCableAudio());
            interlockModificar.setSelected(salon.isInterlock220V());
            nombreModificar.setText(salon.getNombre());
            comboboxTamanoModificar.setSelectedItem(salon.getTamano());
        }

    }//GEN-LAST:event_comboboxSalonesActionPerformed

    private void comboboxProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxProfesoresActionPerformed

        if(comboboxProfesores.getSelectedItem() != null){
            cambiarVisibilidad(true);

            Profesor profesor = (Profesor)comboboxProfesores.getSelectedItem();

            comboboxCarrerasModificarProfesor.setSelectedItem(profesor.getCarrera());
            dniProfesorModificar.setText(profesor.getDni().toString());
            nombreProfesorModificar.setText(profesor.getNombre());
            apellidoProfesorModificar.setText(profesor.getApellido());
        }

    }//GEN-LAST:event_comboboxProfesoresActionPerformed

    private void comboboxCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxCarrerasActionPerformed

        if(comboboxCarreras.getSelectedItem() != null){
            cambiarVisibilidad(true);

            nombreCarreraModificar.setText(((Carrera)comboboxCarreras.getSelectedItem()).getNombre());

        }

    }//GEN-LAST:event_comboboxCarrerasActionPerformed

    private void guardarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProfesorActionPerformed

        new Profesor(Integer.parseInt(dniProfesorAgregar.getText()),
                nombreProfesorAgregar.getText(),
                apellidoProfesorAgregar.getText(),
                (Carrera) comboboxCarrerasAgregar.getSelectedItem()).cargarDatosProfesor();

        dniProfesorAgregar.setText("");
        nombreProfesorAgregar.setText("");
        apellidoProfesorAgregar.setText("");
        comboboxCarrerasAgregar.setSelectedItem(null);

        comboboxProfesores.setModel(new DefaultComboBoxModel<>(profesores.toArray(new Profesor[0])));
        comboboxProfesores.setSelectedItem(null);

    }//GEN-LAST:event_guardarProfesorActionPerformed

    private void modificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProfesorActionPerformed
        Profesor profesor = (Profesor) comboboxProfesores.getSelectedItem();

        profesor.setDni(Integer.parseInt(dniProfesorModificar.getText()));
        profesor.setNombre(nombreProfesorModificar.getText());
        profesor.setApellido(apellidoProfesorModificar.getText());
        profesor.setCarrera((Carrera) comboboxCarrerasModificarProfesor.getSelectedItem());

        cambiarVisibilidad(false);
        comboboxProfesores.setSelectedItem(null);


    }//GEN-LAST:event_modificarProfesorActionPerformed

    private void carreraGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraGuardarActionPerformed

        new Carrera(-1,nombreCarreraAgregar.getText());
        nombreCarreraAgregar.setText("");

        Carrera [] carreras1 = carreras.toArray(new Carrera[0]);
        comboboxCarreras.setModel(new DefaultComboBoxModel<>(carreras1));
        comboboxCarrerasAgregar.setModel(new DefaultComboBoxModel<>(carreras1));
        comboboxCarrerasModificarProfesor.setModel(new DefaultComboBoxModel<>(carreras1));

    }//GEN-LAST:event_carreraGuardarActionPerformed

    private void carreraModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraModificarActionPerformed
        if(comboboxCarreras.getSelectedItem() !=null){

            Carrera carrera = (Carrera) comboboxCarreras.getSelectedItem();
            carrera.setNombre(nombreCarreraModificar.getText());

            nombreCarreraModificar.setText("");
            cambiarVisibilidad(false);

        }
    }//GEN-LAST:event_carreraModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HDMIAgregar;
    private javax.swing.JCheckBox HDMIModificar;
    private javax.swing.JTabbedPane Salones;
    private javax.swing.JCheckBox TVAgregar;
    private javax.swing.JCheckBox TVModificar;
    private javax.swing.JCheckBox VGAAgregar;
    private javax.swing.JCheckBox VGAModificar;
    private javax.swing.JTextField apellidoProfesorAgregar;
    private javax.swing.JTextField apellidoProfesorModificar;
    private javax.swing.JCheckBox audioAgregar;
    private javax.swing.JCheckBox audioModificar;
    private javax.swing.JPasswordField bdPass;
    private javax.swing.JTextField bdURL;
    private javax.swing.JTextField bdUser;
    private javax.swing.JButton botonInterfaz;
    private javax.swing.JButton botonTema;
    private javax.swing.JButton carreraGuardar;
    private javax.swing.JButton carreraModificar;
    private javax.swing.JComboBox<Carrera> comboboxCarrerasModificarProfesor;
    private javax.swing.JComboBox<Carrera> comboboxCarreras;
    private javax.swing.JComboBox<Carrera> comboboxCarrerasAgregar;
    private javax.swing.JComboBox<Profesor> comboboxProfesores;
    private javax.swing.JComboBox<Salon> comboboxSalones;
    private javax.swing.JComboBox<String> comboboxTamanoAgregar;
    private javax.swing.JComboBox<String> comboboxTamanoModificar;
    private javax.swing.JCheckBox conversorAgregar;
    private javax.swing.JCheckBox conversorModificar;
    private javax.swing.JTextField dniProfesorAgregar;
    private javax.swing.JTextField dniProfesorModificar;
    private javax.swing.JButton guardarBD;
    private javax.swing.JButton guardarProfesor;
    private javax.swing.JButton hacerBackup;
    private javax.swing.JCheckBox interlockAgregar;
    private javax.swing.JCheckBox interlockModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton modificarProfesor;
    private javax.swing.JTextField nombreAgregarSalon;
    private javax.swing.JTextField nombreCarreraAgregar;
    private javax.swing.JTextField nombreCarreraModificar;
    private javax.swing.JTextField nombreModificar;
    private javax.swing.JTextField nombreProfesorAgregar;
    private javax.swing.JTextField nombreProfesorModificar;
    private javax.swing.JCheckBox proyectorAgregar;
    private javax.swing.JCheckBox proyectorModificar;
    private javax.swing.JButton restaurarDesdeBackup;
    private javax.swing.JButton salonGuardar;
    private javax.swing.JButton salonModificar;
    private javax.swing.JLayeredPane tabConfiguracion;
    // End of variables declaration//GEN-END:variables
}
